'use client'

import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    // Sidebar
    dashboard: 'Dashboard',
    members: 'Members',
    deposits: 'Deposits',
    externalBorrowers: 'External Borrowers',
    externalLoans: 'External Loans',
    externalLoanPayments: 'External Loan Payments',
    memberLoans: 'Member Loans',
    memberLoanPayments: 'Member Loan Payments',
    reports: 'Reports',
    settings: 'Settings',
    logout: 'Logout',
    adminPortal: 'Admin Portal',
    memberPortal: 'Member Portal',
    
    // Dashboard
    totalMembers: 'Total Members',
    totalNumberDeposits: 'Total Number of Deposits (TND)',
    totalDepositAmount: 'Total Deposit Amount (TDA)',
    todaysCollections: "Today's Collections (TC)",
    totalNumberLoans: 'Total Number of Loans (TNL)',
    activeLoanAccounts: 'Active Loan Accounts (ALA)',
    totalActiveLoanAmount: 'Total Active Loan Amount (TALA)',
    availableBalance: 'Available Balance (AB)',
    externalBorrowingSection: 'External Borrowing Section (EBS)',
    externalBorrowers: 'External Borrowers (EB)',
    externalLoansTotalCount: 'External Loans (Total Count) - EL-TC',
    activeExternalLoans: 'Active External Loans (AEL)',
    externalLoanAmount: 'External Loan Amount (ELA)',
    memberLoansSection: 'Member Loans Section (MLS)',
    memberLoansTotalCount: 'Member Loans (Total Count) - ML-TC',
    activeMemberLoans: 'Active Member Loans (AML)',
    memberLoanAmount: 'Member Loan Amount (MLA)',
    recentDeposits: 'Recent Deposits',
    recentLoans: 'Recent Loans',
    noRecentDeposits: 'No recent deposits',
    noRecentLoans: 'No recent loans',
    addDeposit: 'Add Deposit',
    history: 'History',
    
    // Members
    addMember: 'Add Member',
    editMember: 'Edit Member',
    deleteMember: 'Delete Member',
    closeAccount: 'Close Account',
    closeMemberAccount: 'Close Member Account',
    viewMember: 'View Member',
    name: 'Name',
    phone: 'Phone',
    password: 'Password',
    role: 'Role',
    profile: 'Profile',
    status: 'Status',
    action: 'Action',
    totalDeposit: 'Total Deposit',
    loanStatus: 'Loan Status',
    loanAmount: 'Loan Amount',
    active: 'Active',
    closed: 'Closed',
    paid: 'Paid',
    unpaid: 'Unpaid',
    noLoan: 'No Loan',
    address: 'Address',
    nid: 'NID',
    occupation: 'Occupation',
    monthlyIncome: 'Monthly Income',
    guardianName: 'Guardian Name',
    guardianPhone: 'Guardian Phone',
    joinDate: 'Join Date',
    memberId: 'Member ID',
    memberInfo: 'Member Info',
    financialSummary: 'Financial Summary',
    totalSavings: 'Total Savings / Deposit',
    totalLoan: 'Total Loan / Due',
    fine: 'Fine / Penalty',
    currentBalance: 'Current Balance',
    adjustmentSection: 'Adjustment Section',
    adjustmentType: 'Adjustment Type',
    fullSettlement: 'Full Settlement',
    partialSettlement: 'Partial Settlement',
    forceClose: 'Force Close',
    adjustmentAmount: 'Adjustment Amount',
    notesRemarks: 'Notes / Remarks',
    paymentDetails: 'Payment Details',
    paymentMethod: 'Payment Method',
    handCash: 'Hand Cash',
    bank: 'Bank',
    mobileBanking: 'Mobile Banking',
    transactionId: 'Transaction ID',
    paymentDate: 'Payment Date',
    optional: 'Optional',
    confirmCheckbox: 'I confirm all হিসাব সঠিক এবং যাচাই করা হয়েছে',
    confirmCloseAccount: 'Confirm & Close Account',
    cancel: 'Cancel',
    dateOfBirth: 'Date of Birth',
    
    // Deposits
    addDeposit: 'Add Deposit',
    addPayment: 'Add Payment',
    filterByDate: 'Filter by Date',
    filterByMember: 'Filter by Member',
    clearFilters: 'Clear Filters',
    allMembers: 'All Members',
    date: 'Date',
    member: 'Member',
    amount: 'Amount',
    collector: 'Collector',
    depositHistory: 'Deposit History',
    
    // Loans
    addLoan: 'Add Loan',
    interestRate: 'Interest Rate',
    managementSystem: 'Management System',
    enterPhone: 'Enter phone number',
    enterPassword: 'Enter password',
    loggingIn: 'Logging in...',
    demoCredentials: 'Demo Credentials',
    welcome: 'Welcome',
    accountOverview: "Here's your account overview",
    activeLoans: 'Active Loans',
    pendingPayments: 'Pending Payments',
    monthlySavings: 'Monthly Savings',
    loanStatus: 'Loan Status',
    recentDepositHistory: 'Your recent deposit history...',
    currentLoanInfo: 'Your current loan information...',
    dueDate: 'Due Date',
    loanDetails: 'Loan Details',
    loanId: 'Loan ID',
    principalAmount: 'Principal Amount',
    totalPayable: 'Total Payable',
    paymentHistory: 'Payment History',
    noActiveLoans: 'No active loans found',
    noPaymentsMade: 'No payments made yet',
    enterAmount: 'Enter amount',
    monthlyContribution: 'Monthly Contribution',
    somitiRules: 'Somiti Rules',
    rule1: 'Monthly contribution of ৳500 per member',
    rule2: 'Loans available after 6 months of membership',
    rule3: 'Maximum loan amount: ৳50,000',
    rule4: 'Interest rate: 10% per annum',
    rule5: 'Monthly meetings on first Sunday of every month',
    committee: 'Committee',
    aboutSomiti: 'About Somiti',
    committeeSettings: 'Committee Settings',
    committeeName: 'Committee Name',
    committeeMembers: 'Committee Members',
    somitiOverview: 'Somiti Overview',
    dashboardSummary: 'Dashboard Summary',
    recentDeposits: 'Recent Deposits',
    externalBorrowers: 'External Borrowers',
    externalLoans: 'External Loans',
    memberLoans: 'Member Loans',
    myAccount: 'My Account',
    somiti: 'Somiti',
    overview: 'Overview',
    memberSince: 'Member Since',
    somitiOverview: 'Somiti Overview',
    dashboardSummary: 'Dashboard Summary',
    recentDeposits: 'Recent Deposits',
    externalBorrowers: 'External Borrowers',
    externalLoans: 'External Loans',
    memberLoans: 'Member Loans',
    myAccount: 'My Account',
    somiti: 'Somiti',
    overview: 'Overview',
    memberSince: 'Member Since',
    total: 'Total',
    paid: 'Paid',
    
    // Settings
    depositSettings: 'Deposit Settings',
    organizationSettings: 'Organization Settings',
    defaultDepositAmount: 'Default Daily Deposit Amount',
    depositCollectionTime: 'Deposit Collection Time',
    collectorName: 'Collector Name',
    organizationName: 'Organization Name',
    logo: 'Logo',
    address: 'Address',
    phone: 'Phone',
    email: 'Email',
    businessHours: 'Business Hours',
    currency: 'Currency',
    saveSettings: 'Save Settings',
    
    // Common
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    close: 'Close',
    loading: 'Loading...',
    noData: 'No data available',
  },
  bn: {
    // Sidebar
    dashboard: 'ড্যাশবোর্ড',
    members: 'সদস্যরা',
    deposits: 'ডিপোজিট',
    externalBorrowers: 'বাইরের ঋণগ্রহীতা',
    externalLoans: 'বাইরের ঋণ',
    externalLoanPayments: 'বাইরের ঋণ পরিশোধ',
    memberLoans: 'সদস্য ঋণ',
    memberLoanPayments: 'সদস্য ঋণ পরিশোধ',
    reports: 'রিপোর্ট',
    settings: 'সেটিংস',
    logout: 'লগআউট',
    adminPortal: 'অ্যাডমিন পোর্টাল',
    memberPortal: 'সদস্য পোর্টাল',
    
    // Dashboard
    totalMembers: 'মোট সদস্য',
    totalNumberDeposits: 'মোট ডিপোজিট সংখ্যা (TND)',
    totalDepositAmount: 'মোট ডিপোজিটের পরিমাণ (TDA)',
    todaysCollections: 'আজকের সংগ্রহ (TC)',
    totalNumberLoans: 'মোট ঋণ সংখ্যা (TNL)',
    activeLoanAccounts: 'সক্রিয় ঋণ অ্যাকাউন্ট (ALA)',
    totalActiveLoanAmount: 'মোট সক্রিয় ঋণের পরিমাণ (TALA)',
    availableBalance: 'উপলব্ধ ব্যালেন্স (AB)',
    externalBorrowingSection: 'বাইরের ঋণ বিভাগ (EBS)',
    externalBorrowers: 'বাইরের ঋণগ্রহীতা (EB)',
    externalLoansTotalCount: 'বাইরের ঋণ (মোট সংখ্যা) - EL-TC',
    activeExternalLoans: 'সক্রিয় বাইরের ঋণ (AEL)',
    externalLoanAmount: 'বাইরের ঋণের পরিমাণ (ELA)',
    memberLoansSection: 'সদস্য ঋণ বিভাগ (MLS)',
    memberLoansTotalCount: 'সদস্য ঋণ (মোট সংখ্যা) - ML-TC',
    activeMemberLoans: 'সক্রিয় সদস্য ঋণ (AML)',
    memberLoanAmount: 'সদস্য ঋণের পরিমাণ (MLA)',
    recentDeposits: 'সাম্প্রতিক ডিপোজিট',
    recentLoans: 'সাম্প্রতিক ঋণ',
    noRecentDeposits: 'কোনো সাম্প্রতিক ডিপোজিট নেই',
    noRecentLoans: 'কোনো সাম্প্রতিক ঋণ নেই',
    addDeposit: 'ডিপোজিট যোগ করুন',
    history: 'ইতিহাস',
    
    // Members
    addMember: 'সদস্য যোগ করুন',
    editMember: 'সদস্য সম্পাদনা করুন',
    deleteMember: 'সদস্য মুছুন',
    closeAccount: 'হিসাব বন্ধ করুন',
    closeMemberAccount: 'সদস্যের হিসাব বন্ধ করুন',
    viewMember: 'সদস্য দেখুন',
    name: 'নাম',
    phone: 'ফোন',
    password: 'পাসওয়ার্ড',
    role: 'ভূমিকা',
    profile: 'প্রোফাইল',
    status: 'অবস্থা',
    action: 'কর্ম',
    totalDeposit: 'মোট ডিপোজিট',
    loanStatus: 'ঋণ অবস্থা',
    loanAmount: 'ঋণের পরিমাণ',
    active: 'সক্রিয়',
    closed: 'বন্ধ',
    paid: 'পেইড',
    unpaid: 'অনপেইড',
    noLoan: 'ঋণ নেই',
    address: 'ঠিকানা',
    nid: 'এনআইডি',
    occupation: 'পেশা',
    monthlyIncome: 'মাসিক আয়',
    guardianName: 'গার্ডিয়ান/নমিনি নাম',
    guardianPhone: 'গার্ডিয়ান/নমিনি ফোন',
    joinDate: 'যোগদানের তারিখ',
    memberId: 'সদস্য আইডি',
    memberInfo: 'সদস্য তথ্য',
    financialSummary: 'আর্থিক সারসংক্ষেপ',
    totalSavings: 'মোট সঞ্চয় / ডিপোজিট',
    totalLoan: 'মোট ঋণ / বকেয়া',
    fine: 'জরিমানা',
    currentBalance: 'বর্তমান ব্যালেন্স',
    adjustmentSection: 'সমন্বয় বিভাগ',
    adjustmentType: 'সমন্বয়ের ধরন',
    fullSettlement: 'পূর্ণ নিষ্পত্তি',
    partialSettlement: 'আংশিক নিষ্পত্তি',
    forceClose: 'জোরপূর্বক বন্ধ',
    adjustmentAmount: 'সমন্বয়ের পরিমাণ',
    notesRemarks: 'নোট / মন্তব্য',
    paymentDetails: 'পেমেন্ট বিবরণ',
    paymentMethod: 'পেমেন্ট পদ্ধতি',
    handCash: 'হ্যান্ড ক্যাশ',
    bank: 'ব্যাংক',
    mobileBanking: 'মোবাইল ব্যাংকিং',
    transactionId: 'লেনদেন আইডি',
    paymentDate: 'পেমেন্ট তারিখ',
    optional: 'ঐচ্ছিক',
    confirmCheckbox: 'আমি নিশ্চিত করছি সব হিসাব সঠিক এবং যাচাই করা হয়েছে',
    confirmCloseAccount: 'নিশ্চিত করুন ও হিসাব বন্ধ করুন',
    cancel: 'বাতিল',
    dateOfBirth: 'জন্ম তারিখ',
    
// Deposits
addDeposit: 'ডিপোজিট যোগ করুন',
addPayment: 'পেমেন্ট যোগ করুন',
filterByDate: 'তারিখ অনুযায়ী ফিল্টার',
filterByMember: 'সদস্য অনুযায়ী ফিল্টার',
clearFilters: 'ফিল্টার সাফ করুন',
allMembers: 'সব সদস্য',
date: 'তারিখ',
member: 'সদস্য',
amount: 'পরিমাণ',
collector: 'সংগ্রাহক',
depositHistory: 'আমানত ইতিহাস',
managementSystem: 'ব্যবস্থাপনা ব্যবস্থা',
enterPhone: 'ফোন নম্বর লিখুন',
enterPassword: 'পাসওয়ার্ড লিখুন',
loggingIn: 'লগইন হচ্ছে...',
demoCredentials: 'ডেমো ক্রেডেনশিয়াল',
welcome: 'স্বাগতম',
accountOverview: 'এখানে আপনার অ্যাকাউন্ট ওভারভিউ',
activeLoans: 'সক্রিয় ঋণ',
pendingPayments: 'মুলতুবি পেমেন্ট',
monthlySavings: 'মাসিক সঞ্চয়',
loanStatus: 'ঋণের অবস্থা',
recentDepositHistory: 'আপনার সাম্প্রতিক আমানত ইতিহাস...',
currentLoanInfo: 'আপনার বর্তমান ঋণ তথ্য...',
dueDate: 'মেয়াদ তারিখ',
loanDetails: 'ঋণের বিবরণ',
loanId: 'ঋণ আইডি',
principalAmount: 'মূল পরিমাণ',
totalPayable: 'মোট পরিশোধযোগ্য',
paymentHistory: 'পেমেন্ট ইতিহাস',
noActiveLoans: 'কোনো সক্রিয় ঋণ পাওয়া যায়নি',
noPaymentsMade: 'এখনও কোনো পেমেন্ট করা হয়নি',
enterAmount: 'পরিমাণ লিখুন',
monthlyContribution: 'মাসিক অবদান',
somitiRules: 'সমিতির নিয়মাবলী',
rule1: 'প্রতি সদস্যের জন্য মাসিক ৳৫০০ অবদান',
rule2: '৬ মাসের সদস্যপদের পরে ঋণ পাওয়া যায়',
rule3: 'সর্বোচ্চ ঋণের পরিমাণ: ৳৫০,০০০',
rule4: 'সুদের হার: বছরে ১০%',
rule5: 'প্রতি মাসের প্রথম রবিবারে মাসিক সভা',
committee: 'কমিটি',
aboutSomiti: 'সমিতি সম্পর্কে',
committeeSettings: 'কমিটি সেটিংস',
committeeName: 'কমিটির নাম',
committeeMembers: 'কমিটি সদস্যগণ',
somitiOverview: 'সমিতির ওভারভিউ',
dashboardSummary: 'ড্যাশবোর্ড সারসংক্ষেপ',
    clearFilters: 'ফিল্টার সাফ করুন',
    allMembers: 'সব সদস্য',
    date: 'তারিখ',
    member: 'সদস্য',
    amount: 'পরিমাণ',
    collector: 'সংগ্রাহক',
    depositHistory: 'আমানত ইতিহাস',
    managementSystem: 'ব্যবস্থাপনা ব্যবস্থা',
    enterPhone: 'ফোন নম্বর লিখুন',
    enterPassword: 'পাসওয়ার্ড লিখুন',
    loggingIn: 'লগইন হচ্ছে...',
    demoCredentials: 'ডেমো ক্রেডেনশিয়াল',
    welcome: 'স্বাগতম',
    accountOverview: 'এখানে আপনার অ্যাকাউন্ট ওভারভিউ',
    activeLoans: 'সক্রিয় ঋণ',
    pendingPayments: 'মুলতুবি পেমেন্ট',
    monthlySavings: 'মাসিক সঞ্চয়',
    loanStatus: 'ঋণের অবস্থা',
    recentDepositHistory: 'আপনার সাম্প্রতিক আমানত ইতিহাস...',
    currentLoanInfo: 'আপনার বর্তমান ঋণ তথ্য...',
    dueDate: 'মেয়াদ তারিখ',
    loanDetails: 'ঋণের বিবরণ',
    loanId: 'ঋণ আইডি',
    principalAmount: 'মূল পরিমাণ',
    totalPayable: 'মোট পরিশোধযোগ্য',
    paymentHistory: 'পেমেন্ট ইতিহাস',
    noActiveLoans: 'কোনো সক্রিয় ঋণ পাওয়া যায়নি',
    noPaymentsMade: 'এখনও কোনো পেমেন্ট করা হয়নি',
    enterAmount: 'পরিমাণ লিখুন',
    monthlyContribution: 'মাসিক অবদান',
    somitiRules: 'সমিতির নিয়মাবলী',
    rule1: 'প্রতি সদস্যের জন্য মাসিক ৳৫০০ অবদান',
    rule2: '৬ মাসের সদস্যপদের পরে ঋণ পাওয়া যায়',
    rule3: 'সর্বোচ্চ ঋণের পরিমাণ: ৳৫০,০০০',
    rule4: 'সুদের হার: বছরে ১০%',
    rule5: 'প্রতি মাসের প্রথম রবিবারে মাসিক সভা',
    committee: 'কমিটি',
    aboutSomiti: 'সমিতি সম্পর্কে',
    committeeSettings: 'কমিটি সেটিংস',
    committeeName: 'কমিটির নাম',
    committeeMembers: 'কমিটি সদস্যগণ',
    somitiOverview: 'সমিতির ওভারভিউ',
    dashboardSummary: 'ড্যাশবোর্ড সারসংক্ষেপ',
    
    // Loans
    addLoan: 'ঋণ যোগ করুন',
    interestRate: 'সুদের হার',
    tenure: 'মেয়াদ',
    total: 'মোট',
    paid: 'পরিশোধিত',
    
    // Settings
    depositSettings: 'ডিপোজিট সেটিংস',
    organizationSettings: 'সংস্থা সেটিংস',
    defaultDepositAmount: 'ডিফল্ট দৈনিক ডিপোজিট পরিমাণ',
    depositCollectionTime: 'ডিপোজিট সংগ্রহের সময়',
    collectorName: 'সংগ্রহকারীর নাম',
    organizationName: 'সংস্থার নাম',
    logo: 'লোগো',
    address: 'ঠিকানা',
    phone: 'ফোন',
    email: 'ইমেইল',
    businessHours: 'ব্যবসায়িক সময়',
    currency: 'কারেন্সি',
    saveSettings: 'সেটিংস সংরক্ষণ করুন',
    
    // Common
    cancel: 'বাতিল',
    save: 'সংরক্ষণ',
    delete: 'মুছুন',
    edit: 'সম্পাদনা',
    view: 'দেখুন',
    close: 'বন্ধ',
    loading: 'লোড হচ্ছে...',
    noData: 'কোনো তথ্য নেই',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en')

  const t = (key) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
